-- CREATE TABLE Trulia (
-- 	Index INT NOT NULL,
-- 	Address VARCHAR NOT NULL,
-- 	City VARCHAR NOT NULL,
-- 	State VARCHAR(2) NOT NULL,
-- 	Price VARCHAR NOT NULL,
-- 	SqFt VARCHAR NOT NULL,
-- 	Beds VARCHAR NOT NULL,
-- 	Baths VARCHAR NOT NULL
-- );

-- ALTER TABLE Trulia
-- DROP COLUMN Index;

-- SELECT * FROM Trulia;